" Load plugin initialization
"set shell=cmd.exe
"set shellcmdflag=-c
"set shellslash
"set guioptions+=!     " don't open cmd.exe-window on windows in case of :!

"command! MyPlugUpdate   :set shell=cmd.exe shellcmdflag=/c noshellslash guioptions-=! <bar> noautocmd PlugUpdate
" PlugInstall
"command! MyPlugInstall  :set shell=cmd.exe shellcmdflag=/c noshellslash guioptions-=! <bar> noautocmd PlugInstall
" PlugClean
"command! MyPlugClean    :set shell=cmd.exe shellcmdflag=/c noshellslash guioptions-=! <bar> noaucmd PlugClean

call plug#begin("~/vimfiles/plugged")
" Plugin list
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-commentary'
"Plug 'sheerun/vim-polyglot'
"Plug 'junegunn/fzf'
"Plug 'junegunn/fzf.vim'
Plug 'drewtempelmeyer/palenight.vim' 
call plug#end()

" Leader key
let mapleader = " "

""""""""""""""""""""""""""""""""
" Load plugin configurations """
""""""""""""""""""""""""""""""""

source ~/vimfiles/custom/plugins/palenight.vim

" Load fzf key maps ---
"source ~/vimfiles/custom/plugins/fzf/options.vim
"source ~/vimfiles/custom/plugins/fzf/keymaps.vim
"source ~/vimfiles/custom/plugins/fzf/commands.vim

"""""""""""""""""""""""""""""""""
" Load general configurations """
"""""""""""""""""""""""""""""""""

source ~/vimfiles/custom/options.vim
source ~/vimfiles/custom/keymaps.vim
source ~/vimfiles/custom/ui.vim
" source ~/vimfiles/custom/clipboard.vim

" Add autocommands
source ~/vimfiles/custom/autocmds.vim

" Misc
source ~/vimfiles/custom/misc.vim