services:
  tourbillon_postgres:
    image:  timescale/timescaledb:latest-pg13
    # volumes:
    #   - ~/docker-data/b2e2/tourbillon_postgresql/data:/var/lib/postgresql/data:delegated
    #   - ~/docker-data/b2e2/tourbillon_postgresql-backup/:/db-backup:delegated
    environment:
      - POSTGRES_DB=tourbillon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TS_TUNE_MAX_CONNS=2000
    restart: on-failure
    # ports:
    #   - "5432:5432"

  app_postgres:
    image: postgres:14.6
    volumes:
      # - ~/docker-data/b2e2/app_postgresql/data:/var/lib/postgresql/data:delegated
      # - ~/docker-data/b2e2/app_postgresql-backup/:/db-backup/:delegated
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:delegated
    environment:
      - POSTGRES_DB=geco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    # ports:
    #   - "15432:5432"
    restart: on-failure

  localstack:
    container_name: localstack_main
    image: localstack/localstack
    # ports:
    #   - "4566:4566" # LocalStack Gateway
    #   - "4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=s3,sqs
      - EXTENSION_AUTO_INSTALL=localstack-extension-outages
    volumes:
      - ./tests/setup_scripts:/etc/localstack/init/ready.d
      - ./tests/setup_scripts:/etc/localstack/init/start.d

  redis:
    image: redis
    restart: on-failure
    # ports:
    #   - "6379:6379"

  b2e2:
    container_name: geco-b2e2
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - PIP_INDEX_URL=https://$RES_ARTIFACTORY_USER:$RES_ARTIFACTORY_PASSWORD@artifactory.tools.digital.engie.com/artifactory/api/pypi/gemres-core-pypi-prod/simple
        - PIP_TRUSTED_HOST=artifactory.tools.digital.engie.com
        - VERSION=local
    # volumes:
    #   - ../geco:/app:delegated
    environment:
      - CELERY_BROKER_URL=sqs://user:pass@localstack:4566
      - REDIS_URL=redis://redis:6379/
      - TOURBILLON_POSTGRES_HOST=tourbillon_postgres
      - TOURBILLON_POSTGRES_DB=tourbillon
      - TOURBILLON_POSTGRES_USER=postgres
      - TOURBILLON_POSTGRES_HOST_AUTH_METHOD=trust
      - TOURBILLON_REDIS_HOST=redis
      - TOURBILLON_REDIS_DB=0
      - POSTGRES_POOL_INACTIVE_TIMEOUT=1
      - POSTGRES_POOL_SIZE=5
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@app_postgres/geco
      - FLASK_DEBUG=1
      - OKTA_CLIENT_ID=0oa69jo937azYSbQe0x6
      - OKTA_AUTHORIZATION_BASE_URL=https://gem-beta.oktapreview.com/oauth2/aus3v6rg3e9zNHMxe0x6/v1/authorize
      - OKTA_TOKEN_URL=https://gem-beta.oktapreview.com/oauth2/aus3v6rg3e9zNHMxe0x6/v1/token
      - OKTA_USERINFO_URL=https://gem-beta.oktapreview.com/oauth2/aus3v6rg3e9zNHMxe0x6/v1/userinfo
      - OKTA_REDIRECT_URI=http://localhost:5000/authorization-code/callback
      - OKTA_SCOPE=openid,email,profile,api.backtoearth2
      - OKTA_API_SCOPE=api.backtoearth2
      - OKTA_GROUP_PREFIX=geco-
      - OAUTHLIB_INSECURE_TRANSPORT=True # Used to allow http
      - AWS_ENDPOINT_URL=http://localstack:4566

    env_file:
      - .env
    depends_on:
      - redis
      - tourbillon_postgres
      - app_postgres
      - localstack
    # ports:
    #   - "5000:5000"

  celery:
    image: geco-b2e2
    pull_policy: build
    command: celery -A b2e2.worker_app.celery worker -B --concurrency=10 -l debug
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=sqs://user:pass@localstack:4566
      - REDIS_URL=redis://redis:6379
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@app_postgres/geco
    env_file:
      - .env
    # volumes:
    #   - ../geco:/app:delegated
    depends_on:
      - localstack
      - redis
      - tourbillon_postgres
      - app_postgres

  # celery-flower:
  #   image: geco-b2e2
  #   pull_policy: build
  #   command: bash -c "python -m pip install -U flower && celery -A b2e2.worker_app.celery flower --address=0.0.0.0 --port=5555"
  #   environment:
  #     - CELERY_BROKER_URL=sqs://user:pass@localstack:4566
  #   depends_on:
  #     - redis
  #   # ports:
  #   #   - "5555:5555"

#   mailpit:
#     image: axllent/mailpit
#     container_name: mailpit
#     restart: always
#     volumes:
#       - mailpit_data:/data
#     ports:
#       - 8025:8025
#       - 1025:1025
#     environment:
#       MP_MAX_MESSAGES: 5000
#       MP_DATA_FILE: /data/mailpit.db
#       MP_SMTP_AUTH_ACCEPT_ANY: 1
#       MP_SMTP_AUTH_ALLOW_INSECURE: 1

# volumes:
#   mailpit_data:

